spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: spravesh@gmail.com
    password: vwbu sgfa hbsz qeps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com:
      shaktipravesh:
        journalDemoApp: DEBUG

weather:
  api:
    key: fafaa4355f160b9ea6f0a31aee2a0f36